/* Auto-generated vocabulary bank — 380 words (tech / AI / business / general).
   一整年的每日單字；app.js 依日期挑選，不足一年會循環。
   欲增修：直接在此陣列增加 {term,pos,zh,cat} 即可。*/
const WORDBANK = [
  {"term": "algorithm", "pos": "n.", "zh": "演算法", "cat": "AI"},
  {"term": "model", "pos": "n.", "zh": "模型", "cat": "AI"},
  {"term": "neural network", "pos": "n.", "zh": "神經網路", "cat": "AI"},
  {"term": "deep learning", "pos": "n.", "zh": "深度學習", "cat": "AI"},
  {"term": "machine learning", "pos": "n.", "zh": "機器學習", "cat": "AI"},
  {"term": "training", "pos": "n.", "zh": "訓練", "cat": "AI"},
  {"term": "inference", "pos": "n.", "zh": "推論", "cat": "AI"},
  {"term": "dataset", "pos": "n.", "zh": "資料集", "cat": "AI"},
  {"term": "parameter", "pos": "n.", "zh": "參數", "cat": "AI"},
  {"term": "weight", "pos": "n.", "zh": "權重", "cat": "AI"},
  {"term": "bias", "pos": "n.", "zh": "偏誤", "cat": "AI"},
  {"term": "overfitting", "pos": "n.", "zh": "過度擬合", "cat": "AI"},
  {"term": "underfitting", "pos": "n.", "zh": "擬合不足", "cat": "AI"},
  {"term": "gradient", "pos": "n.", "zh": "梯度", "cat": "AI"},
  {"term": "backpropagation", "pos": "n.", "zh": "反向傳播", "cat": "AI"},
  {"term": "epoch", "pos": "n.", "zh": "訓練週期", "cat": "AI"},
  {"term": "batch", "pos": "n.", "zh": "批次", "cat": "AI"},
  {"term": "tensor", "pos": "n.", "zh": "張量", "cat": "AI"},
  {"term": "embedding", "pos": "n.", "zh": "嵌入向量", "cat": "AI"},
  {"term": "token", "pos": "n.", "zh": "詞元", "cat": "AI"},
  {"term": "tokenizer", "pos": "n.", "zh": "分詞器", "cat": "AI"},
  {"term": "prompt", "pos": "n.", "zh": "提示詞", "cat": "AI"},
  {"term": "fine-tuning", "pos": "n.", "zh": "微調", "cat": "AI"},
  {"term": "pretraining", "pos": "n.", "zh": "預訓練", "cat": "AI"},
  {"term": "transformer", "pos": "n.", "zh": "轉換器架構", "cat": "AI"},
  {"term": "attention", "pos": "n.", "zh": "注意力機制", "cat": "AI"},
  {"term": "hallucination", "pos": "n.", "zh": "幻覺（模型胡謅）", "cat": "AI"},
  {"term": "alignment", "pos": "n.", "zh": "對齊（AI 安全）", "cat": "AI"},
  {"term": "reinforcement learning", "pos": "n.", "zh": "強化學習", "cat": "AI"},
  {"term": "supervised learning", "pos": "n.", "zh": "監督式學習", "cat": "AI"},
  {"term": "unsupervised learning", "pos": "n.", "zh": "非監督式學習", "cat": "AI"},
  {"term": "classification", "pos": "n.", "zh": "分類", "cat": "AI"},
  {"term": "regression", "pos": "n.", "zh": "迴歸", "cat": "AI"},
  {"term": "clustering", "pos": "n.", "zh": "分群", "cat": "AI"},
  {"term": "feature", "pos": "n.", "zh": "特徵", "cat": "AI"},
  {"term": "label", "pos": "n.", "zh": "標籤", "cat": "AI"},
  {"term": "accuracy", "pos": "n.", "zh": "準確率", "cat": "AI"},
  {"term": "precision", "pos": "n.", "zh": "精確率", "cat": "AI"},
  {"term": "recall", "pos": "n.", "zh": "召回率", "cat": "AI"},
  {"term": "benchmark", "pos": "n.", "zh": "基準測試", "cat": "AI"},
  {"term": "latency", "pos": "n.", "zh": "延遲", "cat": "AI"},
  {"term": "throughput", "pos": "n.", "zh": "吞吐量", "cat": "AI"},
  {"term": "generative", "pos": "adj.", "zh": "生成式的", "cat": "AI"},
  {"term": "multimodal", "pos": "adj.", "zh": "多模態的", "cat": "AI"},
  {"term": "agent", "pos": "n.", "zh": "AI 代理程式", "cat": "AI"},
  {"term": "autonomous", "pos": "adj.", "zh": "自主的", "cat": "AI"},
  {"term": "chatbot", "pos": "n.", "zh": "聊天機器人", "cat": "AI"},
  {"term": "computer vision", "pos": "n.", "zh": "電腦視覺", "cat": "AI"},
  {"term": "natural language", "pos": "n.", "zh": "自然語言", "cat": "AI"},
  {"term": "speech recognition", "pos": "n.", "zh": "語音辨識", "cat": "AI"},
  {"term": "generative AI", "pos": "n.", "zh": "生成式人工智慧", "cat": "AI"},
  {"term": "large language model", "pos": "n.", "zh": "大型語言模型", "cat": "AI"},
  {"term": "context window", "pos": "n.", "zh": "上下文視窗", "cat": "AI"},
  {"term": "reasoning", "pos": "n.", "zh": "推理", "cat": "AI"},
  {"term": "synthetic", "pos": "adj.", "zh": "合成的", "cat": "AI"},
  {"term": "annotation", "pos": "n.", "zh": "標註", "cat": "AI"},
  {"term": "guardrail", "pos": "n.", "zh": "防護機制", "cat": "AI"},
  {"term": "robustness", "pos": "n.", "zh": "穩健性", "cat": "AI"},
  {"term": "scalability", "pos": "n.", "zh": "可擴展性", "cat": "AI"},
  {"term": "optimization", "pos": "n.", "zh": "最佳化", "cat": "AI"},
  {"term": "hyperparameter", "pos": "n.", "zh": "超參數", "cat": "AI"},
  {"term": "checkpoint", "pos": "n.", "zh": "檢查點", "cat": "AI"},
  {"term": "quantization", "pos": "n.", "zh": "量化", "cat": "AI"},
  {"term": "distillation", "pos": "n.", "zh": "模型蒸餾", "cat": "AI"},
  {"term": "open-source", "pos": "adj.", "zh": "開放原始碼的", "cat": "AI"},
  {"term": "proprietary", "pos": "adj.", "zh": "專有的", "cat": "AI"},
  {"term": "fairness", "pos": "n.", "zh": "公平性", "cat": "AI"},
  {"term": "interpretability", "pos": "n.", "zh": "可解釋性", "cat": "AI"},
  {"term": "cloud computing", "pos": "n.", "zh": "雲端運算", "cat": "Tech"},
  {"term": "server", "pos": "n.", "zh": "伺服器", "cat": "Tech"},
  {"term": "data center", "pos": "n.", "zh": "資料中心", "cat": "Tech"},
  {"term": "infrastructure", "pos": "n.", "zh": "基礎設施", "cat": "Tech"},
  {"term": "storage", "pos": "n.", "zh": "儲存", "cat": "Tech"},
  {"term": "database", "pos": "n.", "zh": "資料庫", "cat": "Tech"},
  {"term": "query", "pos": "n.", "zh": "查詢", "cat": "Tech"},
  {"term": "pipeline", "pos": "n.", "zh": "資料管線", "cat": "Tech"},
  {"term": "deployment", "pos": "n.", "zh": "部署", "cat": "Tech"},
  {"term": "container", "pos": "n.", "zh": "容器", "cat": "Tech"},
  {"term": "virtualization", "pos": "n.", "zh": "虛擬化", "cat": "Tech"},
  {"term": "bandwidth", "pos": "n.", "zh": "頻寬", "cat": "Tech"},
  {"term": "cache", "pos": "n.", "zh": "快取", "cat": "Tech"},
  {"term": "backup", "pos": "n.", "zh": "備份", "cat": "Tech"},
  {"term": "redundancy", "pos": "n.", "zh": "冗餘備援", "cat": "Tech"},
  {"term": "uptime", "pos": "n.", "zh": "正常運行時間", "cat": "Tech"},
  {"term": "downtime", "pos": "n.", "zh": "停機時間", "cat": "Tech"},
  {"term": "load balancing", "pos": "n.", "zh": "負載平衡", "cat": "Tech"},
  {"term": "provisioning", "pos": "n.", "zh": "資源配置", "cat": "Tech"},
  {"term": "migration", "pos": "n.", "zh": "遷移", "cat": "Tech"},
  {"term": "cluster", "pos": "n.", "zh": "叢集", "cat": "Tech"},
  {"term": "node", "pos": "n.", "zh": "節點", "cat": "Tech"},
  {"term": "endpoint", "pos": "n.", "zh": "端點", "cat": "Tech"},
  {"term": "microservices", "pos": "n.", "zh": "微服務", "cat": "Tech"},
  {"term": "serverless", "pos": "adj.", "zh": "無伺服器的", "cat": "Tech"},
  {"term": "edge computing", "pos": "n.", "zh": "邊緣運算", "cat": "Tech"},
  {"term": "compute", "pos": "n.", "zh": "運算資源", "cat": "Tech"},
  {"term": "workload", "pos": "n.", "zh": "工作負載", "cat": "Tech"},
  {"term": "capacity", "pos": "n.", "zh": "容量", "cat": "Tech"},
  {"term": "provider", "pos": "n.", "zh": "供應商", "cat": "Tech"},
  {"term": "encryption", "pos": "n.", "zh": "加密", "cat": "Tech"},
  {"term": "firewall", "pos": "n.", "zh": "防火牆", "cat": "Tech"},
  {"term": "protocol", "pos": "n.", "zh": "通訊協定", "cat": "Tech"},
  {"term": "packet", "pos": "n.", "zh": "封包", "cat": "Tech"},
  {"term": "gateway", "pos": "n.", "zh": "閘道", "cat": "Tech"},
  {"term": "replication", "pos": "n.", "zh": "資料複寫", "cat": "Tech"},
  {"term": "warehouse", "pos": "n.", "zh": "資料倉儲", "cat": "Tech"},
  {"term": "analytics", "pos": "n.", "zh": "數據分析", "cat": "Tech"},
  {"term": "metadata", "pos": "n.", "zh": "詮釋資料", "cat": "Tech"},
  {"term": "observability", "pos": "n.", "zh": "可觀測性", "cat": "Tech"},
  {"term": "scale", "pos": "v.", "zh": "擴展規模", "cat": "Tech"},
  {"term": "hyperscaler", "pos": "n.", "zh": "超大規模雲端業者", "cat": "Tech"},
  {"term": "software", "pos": "n.", "zh": "軟體", "cat": "Tech"},
  {"term": "hardware", "pos": "n.", "zh": "硬體", "cat": "Tech"},
  {"term": "debug", "pos": "v.", "zh": "除錯", "cat": "Tech"},
  {"term": "compile", "pos": "v.", "zh": "編譯", "cat": "Tech"},
  {"term": "runtime", "pos": "n.", "zh": "執行環境", "cat": "Tech"},
  {"term": "framework", "pos": "n.", "zh": "框架", "cat": "Tech"},
  {"term": "library", "pos": "n.", "zh": "函式庫", "cat": "Tech"},
  {"term": "repository", "pos": "n.", "zh": "程式碼儲存庫", "cat": "Tech"},
  {"term": "version control", "pos": "n.", "zh": "版本控制", "cat": "Tech"},
  {"term": "commit", "pos": "n.", "zh": "提交", "cat": "Tech"},
  {"term": "branch", "pos": "n.", "zh": "分支", "cat": "Tech"},
  {"term": "merge", "pos": "v.", "zh": "合併", "cat": "Tech"},
  {"term": "release", "pos": "n.", "zh": "版本發布", "cat": "Tech"},
  {"term": "patch", "pos": "n.", "zh": "修補程式", "cat": "Tech"},
  {"term": "bug", "pos": "n.", "zh": "程式錯誤", "cat": "Tech"},
  {"term": "refactor", "pos": "v.", "zh": "重構", "cat": "Tech"},
  {"term": "frontend", "pos": "n.", "zh": "前端", "cat": "Tech"},
  {"term": "backend", "pos": "n.", "zh": "後端", "cat": "Tech"},
  {"term": "full-stack", "pos": "adj.", "zh": "全端的", "cat": "Tech"},
  {"term": "interface", "pos": "n.", "zh": "介面", "cat": "Tech"},
  {"term": "module", "pos": "n.", "zh": "模組", "cat": "Tech"},
  {"term": "dependency", "pos": "n.", "zh": "相依套件", "cat": "Tech"},
  {"term": "syntax", "pos": "n.", "zh": "語法", "cat": "Tech"},
  {"term": "variable", "pos": "n.", "zh": "變數", "cat": "Tech"},
  {"term": "function", "pos": "n.", "zh": "函式", "cat": "Tech"},
  {"term": "recursion", "pos": "n.", "zh": "遞迴", "cat": "Tech"},
  {"term": "integration", "pos": "n.", "zh": "整合", "cat": "Tech"},
  {"term": "automation", "pos": "n.", "zh": "自動化", "cat": "Tech"},
  {"term": "cybersecurity", "pos": "n.", "zh": "網路安全", "cat": "Tech"},
  {"term": "vulnerability", "pos": "n.", "zh": "資安漏洞", "cat": "Tech"},
  {"term": "exploit", "pos": "n.", "zh": "漏洞攻擊", "cat": "Tech"},
  {"term": "malware", "pos": "n.", "zh": "惡意軟體", "cat": "Tech"},
  {"term": "phishing", "pos": "n.", "zh": "網路釣魚", "cat": "Tech"},
  {"term": "ransomware", "pos": "n.", "zh": "勒索軟體", "cat": "Tech"},
  {"term": "breach", "pos": "n.", "zh": "資料外洩", "cat": "Tech"},
  {"term": "authentication", "pos": "n.", "zh": "身分驗證", "cat": "Tech"},
  {"term": "authorization", "pos": "n.", "zh": "授權", "cat": "Tech"},
  {"term": "credential", "pos": "n.", "zh": "登入憑證", "cat": "Tech"},
  {"term": "threat", "pos": "n.", "zh": "威脅", "cat": "Tech"},
  {"term": "incident", "pos": "n.", "zh": "資安事件", "cat": "Tech"},
  {"term": "firmware", "pos": "n.", "zh": "韌體", "cat": "Tech"},
  {"term": "sandbox", "pos": "n.", "zh": "沙箱環境", "cat": "Tech"},
  {"term": "chip", "pos": "n.", "zh": "晶片", "cat": "Tech"},
  {"term": "semiconductor", "pos": "n.", "zh": "半導體", "cat": "Tech"},
  {"term": "processor", "pos": "n.", "zh": "處理器", "cat": "Tech"},
  {"term": "GPU", "pos": "n.", "zh": "圖形處理器", "cat": "Tech"},
  {"term": "CPU", "pos": "n.", "zh": "中央處理器", "cat": "Tech"},
  {"term": "transistor", "pos": "n.", "zh": "電晶體", "cat": "Tech"},
  {"term": "wafer", "pos": "n.", "zh": "晶圓", "cat": "Tech"},
  {"term": "fabrication", "pos": "n.", "zh": "晶片製造", "cat": "Tech"},
  {"term": "foundry", "pos": "n.", "zh": "晶圓代工廠", "cat": "Tech"},
  {"term": "nanometer", "pos": "n.", "zh": "奈米", "cat": "Tech"},
  {"term": "circuit", "pos": "n.", "zh": "電路", "cat": "Tech"},
  {"term": "memory", "pos": "n.", "zh": "記憶體", "cat": "Tech"},
  {"term": "sensor", "pos": "n.", "zh": "感測器", "cat": "Tech"},
  {"term": "yield", "pos": "n.", "zh": "良率", "cat": "Tech"},
  {"term": "lithography", "pos": "n.", "zh": "微影技術", "cat": "Tech"},
  {"term": "packaging", "pos": "n.", "zh": "晶片封裝", "cat": "Tech"},
  {"term": "accelerator", "pos": "n.", "zh": "運算加速器", "cat": "Tech"},
  {"term": "supply chain", "pos": "n.", "zh": "供應鏈", "cat": "Tech"},
  {"term": "component", "pos": "n.", "zh": "零組件", "cat": "Tech"},
  {"term": "device", "pos": "n.", "zh": "裝置", "cat": "Tech"},
  {"term": "prototype", "pos": "n.", "zh": "原型", "cat": "Tech"},
  {"term": "wearable", "pos": "n.", "zh": "穿戴式裝置", "cat": "Tech"},
  {"term": "robotics", "pos": "n.", "zh": "機器人技術", "cat": "Tech"},
  {"term": "quantum computing", "pos": "n.", "zh": "量子運算", "cat": "Tech"},
  {"term": "battery", "pos": "n.", "zh": "電池", "cat": "Tech"},
  {"term": "bottleneck", "pos": "n.", "zh": "瓶頸", "cat": "Tech"},
  {"term": "throughput rate", "pos": "n.", "zh": "產出率", "cat": "Tech"},
  {"term": "revenue", "pos": "n.", "zh": "營收", "cat": "Business"},
  {"term": "profit", "pos": "n.", "zh": "利潤", "cat": "Business"},
  {"term": "margin", "pos": "n.", "zh": "利潤率", "cat": "Business"},
  {"term": "earnings", "pos": "n.", "zh": "盈餘", "cat": "Business"},
  {"term": "cost", "pos": "n.", "zh": "成本", "cat": "Business"},
  {"term": "budget", "pos": "n.", "zh": "預算", "cat": "Business"},
  {"term": "forecast", "pos": "n.", "zh": "預測", "cat": "Business"},
  {"term": "capital", "pos": "n.", "zh": "資本", "cat": "Business"},
  {"term": "investment", "pos": "n.", "zh": "投資", "cat": "Business"},
  {"term": "investor", "pos": "n.", "zh": "投資人", "cat": "Business"},
  {"term": "shareholder", "pos": "n.", "zh": "股東", "cat": "Business"},
  {"term": "stakeholder", "pos": "n.", "zh": "利害關係人", "cat": "Business"},
  {"term": "equity", "pos": "n.", "zh": "股權", "cat": "Business"},
  {"term": "valuation", "pos": "n.", "zh": "估值", "cat": "Business"},
  {"term": "market cap", "pos": "n.", "zh": "市值", "cat": "Business"},
  {"term": "stock", "pos": "n.", "zh": "股票", "cat": "Business"},
  {"term": "dividend", "pos": "n.", "zh": "股利", "cat": "Business"},
  {"term": "IPO", "pos": "n.", "zh": "首次公開發行", "cat": "Business"},
  {"term": "acquisition", "pos": "n.", "zh": "收購", "cat": "Business"},
  {"term": "merger", "pos": "n.", "zh": "合併", "cat": "Business"},
  {"term": "asset", "pos": "n.", "zh": "資產", "cat": "Business"},
  {"term": "liability", "pos": "n.", "zh": "負債", "cat": "Business"},
  {"term": "cash flow", "pos": "n.", "zh": "現金流", "cat": "Business"},
  {"term": "liquidity", "pos": "n.", "zh": "流動性", "cat": "Business"},
  {"term": "debt", "pos": "n.", "zh": "債務", "cat": "Business"},
  {"term": "interest rate", "pos": "n.", "zh": "利率", "cat": "Business"},
  {"term": "inflation", "pos": "n.", "zh": "通貨膨脹", "cat": "Business"},
  {"term": "recession", "pos": "n.", "zh": "經濟衰退", "cat": "Business"},
  {"term": "GDP", "pos": "n.", "zh": "國內生產毛額", "cat": "Business"},
  {"term": "supply", "pos": "n.", "zh": "供給", "cat": "Business"},
  {"term": "demand", "pos": "n.", "zh": "需求", "cat": "Business"},
  {"term": "monopoly", "pos": "n.", "zh": "壟斷", "cat": "Business"},
  {"term": "subsidy", "pos": "n.", "zh": "補貼", "cat": "Business"},
  {"term": "tariff", "pos": "n.", "zh": "關稅", "cat": "Business"},
  {"term": "quarter", "pos": "n.", "zh": "季度", "cat": "Business"},
  {"term": "fiscal", "pos": "adj.", "zh": "財政的", "cat": "Business"},
  {"term": "overhead", "pos": "n.", "zh": "營運間接成本", "cat": "Business"},
  {"term": "depreciation", "pos": "n.", "zh": "折舊", "cat": "Business"},
  {"term": "portfolio", "pos": "n.", "zh": "投資組合", "cat": "Business"},
  {"term": "hedge", "pos": "n.", "zh": "避險", "cat": "Business"},
  {"term": "volatility", "pos": "n.", "zh": "波動性", "cat": "Business"},
  {"term": "guidance", "pos": "n.", "zh": "財測展望", "cat": "Business"},
  {"term": "capex", "pos": "n.", "zh": "資本支出", "cat": "Business"},
  {"term": "opex", "pos": "n.", "zh": "營運支出", "cat": "Business"},
  {"term": "ROI", "pos": "n.", "zh": "投資報酬率", "cat": "Business"},
  {"term": "revenue stream", "pos": "n.", "zh": "收入來源", "cat": "Business"},
  {"term": "break-even", "pos": "n.", "zh": "損益兩平", "cat": "Business"},
  {"term": "turnover", "pos": "n.", "zh": "營業額", "cat": "Business"},
  {"term": "stakeholder value", "pos": "n.", "zh": "利害關係人價值", "cat": "Business"},
  {"term": "startup", "pos": "n.", "zh": "新創公司", "cat": "Business"},
  {"term": "entrepreneur", "pos": "n.", "zh": "創業家", "cat": "Business"},
  {"term": "venture capital", "pos": "n.", "zh": "創業投資", "cat": "Business"},
  {"term": "funding", "pos": "n.", "zh": "資金", "cat": "Business"},
  {"term": "seed round", "pos": "n.", "zh": "種子輪募資", "cat": "Business"},
  {"term": "unicorn", "pos": "n.", "zh": "獨角獸新創", "cat": "Business"},
  {"term": "pivot", "pos": "v.", "zh": "轉型", "cat": "Business"},
  {"term": "runway", "pos": "n.", "zh": "資金可維持期", "cat": "Business"},
  {"term": "burn rate", "pos": "n.", "zh": "資金消耗率", "cat": "Business"},
  {"term": "bootstrap", "pos": "v.", "zh": "自力籌資", "cat": "Business"},
  {"term": "disrupt", "pos": "v.", "zh": "顛覆", "cat": "Business"},
  {"term": "innovation", "pos": "n.", "zh": "創新", "cat": "Business"},
  {"term": "product", "pos": "n.", "zh": "產品", "cat": "Business"},
  {"term": "launch", "pos": "n.", "zh": "上市發表", "cat": "Business"},
  {"term": "roadmap", "pos": "n.", "zh": "產品藍圖", "cat": "Business"},
  {"term": "milestone", "pos": "n.", "zh": "里程碑", "cat": "Business"},
  {"term": "strategy", "pos": "n.", "zh": "策略", "cat": "Business"},
  {"term": "execution", "pos": "n.", "zh": "執行力", "cat": "Business"},
  {"term": "customer", "pos": "n.", "zh": "顧客", "cat": "Business"},
  {"term": "client", "pos": "n.", "zh": "客戶", "cat": "Business"},
  {"term": "retention", "pos": "n.", "zh": "顧客留存", "cat": "Business"},
  {"term": "churn", "pos": "n.", "zh": "客戶流失率", "cat": "Business"},
  {"term": "conversion", "pos": "n.", "zh": "轉換率", "cat": "Business"},
  {"term": "funnel", "pos": "n.", "zh": "行銷漏斗", "cat": "Business"},
  {"term": "lead", "pos": "n.", "zh": "潛在客戶", "cat": "Business"},
  {"term": "engagement", "pos": "n.", "zh": "互動參與", "cat": "Business"},
  {"term": "branding", "pos": "n.", "zh": "品牌經營", "cat": "Business"},
  {"term": "campaign", "pos": "n.", "zh": "行銷活動", "cat": "Business"},
  {"term": "target audience", "pos": "n.", "zh": "目標受眾", "cat": "Business"},
  {"term": "segment", "pos": "n.", "zh": "市場區隔", "cat": "Business"},
  {"term": "outreach", "pos": "n.", "zh": "拓展接觸", "cat": "Business"},
  {"term": "subscription", "pos": "n.", "zh": "訂閱制", "cat": "Business"},
  {"term": "onboarding", "pos": "n.", "zh": "新手上手", "cat": "Business"},
  {"term": "deliverable", "pos": "n.", "zh": "交付成果", "cat": "Business"},
  {"term": "deadline", "pos": "n.", "zh": "截止期限", "cat": "Business"},
  {"term": "workflow", "pos": "n.", "zh": "工作流程", "cat": "Business"},
  {"term": "productivity", "pos": "n.", "zh": "生產力", "cat": "Business"},
  {"term": "collaboration", "pos": "n.", "zh": "協作", "cat": "Business"},
  {"term": "remote work", "pos": "n.", "zh": "遠距工作", "cat": "Business"},
  {"term": "outsourcing", "pos": "n.", "zh": "外包", "cat": "Business"},
  {"term": "negotiation", "pos": "n.", "zh": "談判", "cat": "Business"},
  {"term": "partnership", "pos": "n.", "zh": "合夥關係", "cat": "Business"},
  {"term": "compliance", "pos": "n.", "zh": "法規遵循", "cat": "Business"},
  {"term": "governance", "pos": "n.", "zh": "治理", "cat": "Business"},
  {"term": "scale-up", "pos": "n.", "zh": "擴張期公司", "cat": "Business"},
  {"term": "bond", "pos": "n.", "zh": "債券", "cat": "Business"},
  {"term": "yield curve", "pos": "n.", "zh": "殖利率曲線", "cat": "Business"},
  {"term": "collateral", "pos": "n.", "zh": "擔保品", "cat": "Business"},
  {"term": "underwrite", "pos": "v.", "zh": "承銷／核保", "cat": "Business"},
  {"term": "amortization", "pos": "n.", "zh": "攤銷", "cat": "Business"},
  {"term": "accrual", "pos": "n.", "zh": "應計項目", "cat": "Business"},
  {"term": "audit", "pos": "n.", "zh": "財務查核", "cat": "Business"},
  {"term": "ledger", "pos": "n.", "zh": "帳本", "cat": "Business"},
  {"term": "invoice", "pos": "n.", "zh": "請款單", "cat": "Business"},
  {"term": "procurement", "pos": "n.", "zh": "採購", "cat": "Business"},
  {"term": "logistics", "pos": "n.", "zh": "物流", "cat": "Business"},
  {"term": "inventory", "pos": "n.", "zh": "庫存", "cat": "Business"},
  {"term": "wholesale", "pos": "n.", "zh": "批發", "cat": "Business"},
  {"term": "retail", "pos": "n.", "zh": "零售", "cat": "Business"},
  {"term": "markup", "pos": "n.", "zh": "加價", "cat": "Business"},
  {"term": "commodity", "pos": "n.", "zh": "大宗商品", "cat": "Business"},
  {"term": "arbitrage", "pos": "n.", "zh": "套利", "cat": "Business"},
  {"term": "solvency", "pos": "n.", "zh": "償債能力", "cat": "Business"},
  {"term": "creditworthiness", "pos": "n.", "zh": "信用評等度", "cat": "Business"},
  {"term": "leverage ratio", "pos": "n.", "zh": "槓桿比率", "cat": "Business"},
  {"term": "wireframe", "pos": "n.", "zh": "線框稿", "cat": "Business"},
  {"term": "mockup", "pos": "n.", "zh": "設計樣稿", "cat": "Business"},
  {"term": "usability", "pos": "n.", "zh": "易用性", "cat": "Business"},
  {"term": "accessibility", "pos": "n.", "zh": "無障礙性", "cat": "Business"},
  {"term": "A/B testing", "pos": "n.", "zh": "A/B 測試", "cat": "Business"},
  {"term": "cohort", "pos": "n.", "zh": "世代分析群", "cat": "Business"},
  {"term": "dashboard", "pos": "n.", "zh": "儀表板", "cat": "Business"},
  {"term": "KPI", "pos": "n.", "zh": "關鍵績效指標", "cat": "Business"},
  {"term": "OKR", "pos": "n.", "zh": "目標與關鍵成果", "cat": "Business"},
  {"term": "backlog", "pos": "n.", "zh": "待辦清單", "cat": "Business"},
  {"term": "sprint", "pos": "n.", "zh": "衝刺開發週期", "cat": "Business"},
  {"term": "agile", "pos": "adj.", "zh": "敏捷式的", "cat": "Business"},
  {"term": "scrum", "pos": "n.", "zh": "Scrum 開發框架", "cat": "Business"},
  {"term": "stand-up", "pos": "n.", "zh": "每日站立會議", "cat": "Business"},
  {"term": "retrospective", "pos": "n.", "zh": "回顧會議", "cat": "Business"},
  {"term": "value proposition", "pos": "n.", "zh": "價值主張", "cat": "Business"},
  {"term": "competitive advantage", "pos": "n.", "zh": "競爭優勢", "cat": "Business"},
  {"term": "market share", "pos": "n.", "zh": "市場占有率", "cat": "Business"},
  {"term": "differentiation", "pos": "n.", "zh": "差異化", "cat": "Business"},
  {"term": "positioning", "pos": "n.", "zh": "市場定位", "cat": "Business"},
  {"term": "go-to-market", "pos": "n.", "zh": "市場進入策略", "cat": "Business"},
  {"term": "monetize", "pos": "v.", "zh": "變現", "cat": "Business"},
  {"term": "economies of scale", "pos": "n.", "zh": "規模經濟", "cat": "Business"},
  {"term": "delegate", "pos": "v.", "zh": "授權分工", "cat": "Business"},
  {"term": "mentor", "pos": "n.", "zh": "導師", "cat": "Business"},
  {"term": "feedback", "pos": "n.", "zh": "回饋", "cat": "Business"},
  {"term": "performance review", "pos": "n.", "zh": "績效考核", "cat": "Business"},
  {"term": "morale", "pos": "n.", "zh": "團隊士氣", "cat": "Business"},
  {"term": "turnover rate", "pos": "n.", "zh": "離職率", "cat": "Business"},
  {"term": "recruitment", "pos": "n.", "zh": "招募", "cat": "Business"},
  {"term": "headcount", "pos": "n.", "zh": "員工人數", "cat": "Business"},
  {"term": "stakeholder buy-in", "pos": "n.", "zh": "關鍵人物支持", "cat": "Business"},
  {"term": "upskilling", "pos": "n.", "zh": "技能提升", "cat": "Business"},
  {"term": "burnout", "pos": "n.", "zh": "職業倦怠", "cat": "Business"},
  {"term": "work-life balance", "pos": "n.", "zh": "工作與生活平衡", "cat": "Business"},
  {"term": "accountability", "pos": "n.", "zh": "當責", "cat": "Business"},
  {"term": "empowerment", "pos": "n.", "zh": "賦能", "cat": "Business"},
  {"term": "alignment meeting", "pos": "n.", "zh": "共識會議", "cat": "Business"},
  {"term": "implement", "pos": "v.", "zh": "實作／實施", "cat": "General"},
  {"term": "enhance", "pos": "v.", "zh": "增強", "cat": "General"},
  {"term": "leverage", "pos": "v.", "zh": "善用", "cat": "General"},
  {"term": "optimize", "pos": "v.", "zh": "最佳化", "cat": "General"},
  {"term": "streamline", "pos": "v.", "zh": "精簡流程", "cat": "General"},
  {"term": "facilitate", "pos": "v.", "zh": "促進", "cat": "General"},
  {"term": "mitigate", "pos": "v.", "zh": "減輕", "cat": "General"},
  {"term": "prioritize", "pos": "v.", "zh": "排定優先順序", "cat": "General"},
  {"term": "allocate", "pos": "v.", "zh": "分配", "cat": "General"},
  {"term": "evaluate", "pos": "v.", "zh": "評估", "cat": "General"},
  {"term": "assess", "pos": "v.", "zh": "評估", "cat": "General"},
  {"term": "demonstrate", "pos": "v.", "zh": "展示", "cat": "General"},
  {"term": "significant", "pos": "adj.", "zh": "顯著的", "cat": "General"},
  {"term": "substantial", "pos": "adj.", "zh": "可觀的", "cat": "General"},
  {"term": "robust", "pos": "adj.", "zh": "穩健的", "cat": "General"},
  {"term": "comprehensive", "pos": "adj.", "zh": "全面的", "cat": "General"},
  {"term": "sustainable", "pos": "adj.", "zh": "可持續的", "cat": "General"},
  {"term": "feasible", "pos": "adj.", "zh": "可行的", "cat": "General"},
  {"term": "viable", "pos": "adj.", "zh": "可行的", "cat": "General"},
  {"term": "emerging", "pos": "adj.", "zh": "新興的", "cat": "General"},
  {"term": "disruptive", "pos": "adj.", "zh": "顛覆性的", "cat": "General"},
  {"term": "cutting-edge", "pos": "adj.", "zh": "尖端的", "cat": "General"},
  {"term": "seamless", "pos": "adj.", "zh": "順暢無縫的", "cat": "General"},
  {"term": "transparent", "pos": "adj.", "zh": "透明的", "cat": "General"},
  {"term": "accountable", "pos": "adj.", "zh": "當責的", "cat": "General"},
  {"term": "resilient", "pos": "adj.", "zh": "有韌性的", "cat": "General"},
  {"term": "strategic", "pos": "adj.", "zh": "策略性的", "cat": "General"},
  {"term": "innovative", "pos": "adj.", "zh": "創新的", "cat": "General"},
  {"term": "efficient", "pos": "adj.", "zh": "有效率的", "cat": "General"},
  {"term": "proactive", "pos": "adj.", "zh": "積極主動的", "cat": "General"},
  {"term": "insight", "pos": "n.", "zh": "洞見", "cat": "General"},
  {"term": "trend", "pos": "n.", "zh": "趨勢", "cat": "General"},
  {"term": "metric", "pos": "n.", "zh": "衡量指標", "cat": "General"},
  {"term": "outcome", "pos": "n.", "zh": "結果", "cat": "General"},
  {"term": "impact", "pos": "n.", "zh": "影響", "cat": "General"},
  {"term": "initiative", "pos": "n.", "zh": "主動作為", "cat": "General"},
  {"term": "paradigm", "pos": "n.", "zh": "典範", "cat": "General"},
  {"term": "ecosystem", "pos": "n.", "zh": "生態系", "cat": "General"},
  {"term": "momentum", "pos": "n.", "zh": "動能", "cat": "General"},
  {"term": "threshold", "pos": "n.", "zh": "門檻", "cat": "General"},
  {"term": "trajectory", "pos": "n.", "zh": "走勢", "cat": "General"},
  {"term": "consensus", "pos": "n.", "zh": "共識", "cat": "General"},
  {"term": "adoption", "pos": "n.", "zh": "採用", "cat": "General"},
  {"term": "transition", "pos": "n.", "zh": "轉變", "cat": "General"},
  {"term": "scalable", "pos": "adj.", "zh": "可擴展的", "cat": "General"},
  {"term": "breakthrough", "pos": "n.", "zh": "突破", "cat": "General"},
  {"term": "bottleneck removal", "pos": "n.", "zh": "瓶頸排除", "cat": "General"},
  {"term": "iteration", "pos": "n.", "zh": "反覆改良", "cat": "General"},
  {"term": "benchmark result", "pos": "n.", "zh": "基準結果", "cat": "General"},
];
